### ISSUE TITLE
Rainmeter: Unable to move to.

### ISSUE THREAD

**Issue by Herwork06** [Jax-Core/Keylaunch#1]
![image](https://user-images.githubusercontent.com/68442634/150548150-f0854530-b1fc-4de9-abea-f402c6c1feb1.png)

**Comment by Herwork06** [comment]
Fixed it!
Solution:
Delete the folder and reinstall it again

**Comment by EnhancedJax** [comment]
Closing the module first before installing would also solve this issue.
