### ISSUE TITLE
Can't edit any of the actions' hotkeys

### ISSUE THREAD

**Issue by itschark** [Jax-Core/Keylaunch#3]
I am trying to use Keylaunch for some files and images and I suddenly can't edit my hotkeys. Does anyone know what the problem is?

**Comment by EnhancedJax** [comment]
Are you on the latest version of Core?

**Comment by itschark** [comment]
> Are you on the latest version of Core?

yes i am.
for some reason it works now but sometimes it does that and i dont know why
